### ISSUE TITLE
USER STORY: Mentor Start of Project Session

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#15]
As a **Developer** I can **discuss my concept study for my PP4 app with my mentor** so that **I get feedback and possible improvements or guidelines in order to actually start coding my app**

## Acceptance Criteria
- [ ] My PP4 idea is presented to mentor including Wireframes, ERD, Epics
- [ ] Already open questions are addressed
- [ ] Feedback of mentor is understood,  project roadmap epics, stories are updated accordingly

## Tasks
- [ ] Present Wireframes, ERD, Agile Board and my Ideas
- [ ] Ask questions
- [ ] Note feedback and update project accordingly

**Comment by rpf13** [comment]
Start of Project mentor session took place on 6.4.23
