### ISSUE TITLE
USER STORY: Mentor Midway Project Session

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#16]
As a **Developer** I can **show the status of my PP4 to my mentor** so that **I can receive valuable feedback and guidance for the rest of the project phase**

## Acceptance Criteria
- [x] Midway Project status is presented and all open questions are addressed
- [x] Feedback is received and possible additional tasks are created
- [x] Open bugs are discussed (if necessary)
- [x] Further path is clear

## Tasks
- [x] Demonstrate project status
- [x] Update all docs, code and deployment in order for mentor to check
- [x] prepare all questions, bugs
