### ISSUE TITLE
USER STORY: Mentor End of Project Session

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#17]
As a **Developer** I can **present my finished project and (almost) finished documentation** so that **I can get valuable feedback of my mentor**

## Acceptance Criteria
- [x] Final (deployed) project is presented including documentation
- [x] Open questions are discussed and solution is understood
- [x] Scope is checked including key assessment criterias
- [x] App will be ready to submit after implementing this feedback

## Tasks
- [x] Prepare code and documentation to present
- [x] Update agile board
- [x] Update documentation
- [x] Prepare open questions and bugs

**Comment by rpf13** [comment]
Final mentor session took place, story can be closed.
