### ISSUE TITLE
USER STORY: Django installation & app

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#18]
As a **Developer** I can **install Django and create the base app** so that **I have the base setup**

## Acceptance Criteria
- [x] Django 3.x installed & running on Gitpod
- [x] Dependencies installed and fixed in the requirements.txt file

## Tasks
- [x] Install Django 3.x
- [x] Create the_collection app
- [x] Install Gunicorn - pip3 install django gunicorn
- [x] Install psychopg2 - pip3 install dj_database_url psycopg2
- [x] Install cloudinary - pip3 install dj3-cloudinary-storage
- [x] Install summernote - pip3 install django-summernote
- [x] Install allauth - pip3 install django-allauth
- [x] (install crispy forms - pip3 install django-crispy-forms) -> not sure
- [x] create req file: pip3 freeze --local > requirements.txt
