### ISSUE TITLE
USER STORY: Setup Environment Variables

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#19]
As a **Developer** I can **create the env.py file and setup the .gitignore file** so that **I have a secure environment, which I can deploy on heroku**

## Acceptance Criteria
- [ ] env.py created with all variables
- [ ] settings.py updated accordingly
- [ ] all settings ready to execute initial deploy

## Tasks
- [ ] create env.py with db secret, cloudinary api key, db path
- [ ] check that env.py is in .gitignoer file
- [ ] verify debug settings
- [ ] check all other paths

**Comment by rpf13** [comment]
- Cloudinary settngs added for file storage
- Initial deployment on Heroku is done, including all settings of config vars
- temporary set the debug = true on heroku in order to verify successful deployment

![Image](https://user-images.githubusercontent.com/25194462/231107687-bad51040-4d95-4a89-bbf6-bf88d7806952.png)
