### ISSUE TITLE
USER STORY: Heroku initial deployment

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#20]
As a **Developer** I can **deploy the site on Heroku** so that **I can verify at an early stage, that the setup is correct as well as give the mentor the option to check the live state during the mid project session**

## Acceptance Criteria
- [ ] Heroku app created including vars
- [ ] Functionality verified
- [ ] Automatic GithHub deployment enabled

## Tasks
- [ ] App on Heroku is created
- [ ] Links to database and cloudinary done
- [ ] Secret key is added
- [ ] Gitpod and Heroku deployment are "inline", using the same resources
- [ ]

**Comment by rpf13** [comment]
Heroku app created, config vars set and automatic deployment for github done.
All links have been updated, env.py settings are copied to config vars (urls, passwords).
Temporarily set the debug = true on heroku to see proper deployment.


![Image](https://user-images.githubusercontent.com/25194462/231159576-1fdf77af-6433-434c-91df-084427f233d6.png)
