### ISSUE TITLE
USER STORY: ElephantSQL Setup

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#21]
As a **Developer** I can **setup a new ElephantSQL instance** so that **I can link it to my App in order to have a SQL database**

## Acceptance Criteria
- [ ] ElephantSQL instance created and linked to Heroku / Gitpod
- [ ] 
- [ ] 

## Tasks
- [ ] Create new ElephantSQL instance
- [ ] Link it to Heroku and Gitpod incl. all keys and env. variables
- [ ] Make sure same DB is used for prod and dev environment
- [ ]

**Comment by rpf13** [comment]
ElephantSQL instance created and linked ot heroku and gitpod, env.py created and int gitignore.
