### ISSUE TITLE
USER STORY: Cloudinary Setup

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#22]
As a **Developer** I can **setup a new cloudinary instance** so that **I can link it to my app and use it for all the media content of my project**

## Acceptance Criteria
- [ ] Cloudinary instance created and linked to project
- [ ] 
- [ ] 

## Tasks
- [ ] Create new instance on Cloudinary
- [ ] Link api key in django settings
- [ ] Verify functionality
