### ISSUE TITLE
USER STORY: New User Registration

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#23]
As a **user** I can **register an account** so that **I can create, update, delete a new collection and the individual items**

## Acceptance Criteria
- [x] Signup button is implemented and I get redirected to the signup form
- [x] After filling in all fields and submit the form, my new account is created and I can start using the app
- [ ] I get a notification (modal) that my account is created

## Tasks
- [x] Install allauth and add to installed apps
- [x] verify underlying model
- [x] extend the base template / create a new one for the signup form
- [ ] create notification messages

**Comment by rpf13** [comment]
Allauth simple setup is done, via a simple view just to verify the signup process.
Some old templates from another project are also copied, just to verify functionality, will be replaced later.
Commit ID: b6b8395


![Image](https://user-images.githubusercontent.com/25194462/231413159-78eb246c-b13e-4327-987a-4fc39544a724.png)

**Comment by rpf13** [comment]
Style of "raw" template has been enhanced, however, still not final.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
Notifications are stretch, might be implemented later.

**Comment by rpf13** [comment]
Messages will not be implemented, it would be kind of distract the current design and for the functionality given, the are not necessary.
Story will be closed.
