### ISSUE TITLE
USER STORY: User Login & Logout

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#24]
As a **user** I can **login & logout of my account** so that **my account is secured and no one else has access to my collections**

## Acceptance Criteria
- [x] user can login via dedicated login button in navbar
- [ ] user gets a message that he is logged in
- [ ] incorrect values should lead to displayed error message
- [x] user can logout via dedicated logut button in navbar
- [ ] after logout, user gets a message that he is logged out

## Tasks
- [x] update templates in navbar for login and logout
- [x] update allauth construct if necessary
- [ ] create messages for login/logout

**Comment by rpf13** [comment]
Allauth simple setup is done, via a simple view just to verify the login/logout process.
Some old templates from another project are also copied, just to verify functionality, will be replaced later.
Commit ID: b6b8395


![Image](https://user-images.githubusercontent.com/25194462/231413574-b47a52c4-a0cd-44f1-a1f9-4b875cf7b6e6.png)

**Comment by rpf13** [comment]
Further enhancements for authorization process, did create a base template and a base, main site, to which the user gets directed when entering the site.
Authorization templates got adapted with basic styling via bootstrap (will be enhanced later) and it is now possible to signup, login, logout with a user.
All links in navbar and the main site are updated.
Commit id: main 8591489

Example styling:


![Image](https://user-images.githubusercontent.com/25194462/231708272-067a47e8-cd91-4508-b75d-7c7f693539e9.png)

**Comment by rpf13** [comment]
Messages will not be implemented, it would be kind of distract the current design and for the functionality given, the are not necessary.
Story will be closed.
