### ISSUE TITLE
USER STORY: User Status

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#25]
As a **user** I can **see the status of authentication int he navbar** so that **I can easily see whether I am logged in or not**

## Acceptance Criteria
- [x] update navbar template with logic to see if user is logged in or not
- [x] display status accordingly on navbar
- [x] display user name in navbar if logged in

## Tasks
- [x] create authentication logic in template
- [x] update the template, code in the way that user state gets displayed
