### ISSUE TITLE
USER STORY: Admin User Setup

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#26]
As a **Admin** I can **login to the django admin panel** so that **I can administer each user and or delete a user if his content is inappropriate or violates terms and conditions**

## Acceptance Criteria
- [ ] admin user is able to login to django admin panel
- [ ] admin user can see all accounts of users and can edit/delete them
- [ ] 

## Tasks
- [ ] create / update django admin user
- [ ] register the user model to admin site
- [ ] update all settings as necessary
- [ ] edit admin django settings if necessary
