### ISSUE TITLE
USER STORY: User can edit his Profile

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#27]
As a **user** I can **edit my profile settings** so that **I can update and administer my account**

## Acceptance Criteria
- [ ] user can click on edit profile in the navbar
- [ ] user can change key profile settings like name, ...
- [ ] 

## Tasks
- [ ] create a new / extend template to have an edit profile site
- [ ] implement logic (to be verified) that a user can edit his profile
- [ ] adjust model or settings accordingly (to be researched)
- [ ] create message that user gets notified about his profile change
