### ISSUE TITLE
USER STORY: Create base template

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#28]
As a **Developer** I can **create the base html template** so that **I can get a default main page and have the base concept / styling for all the subsequent sites**

## Acceptance Criteria
- [x] All fonts, colors are defined and set
- [x] Base html template is done using bootstrap
- [x] Main site will display login / create account button
- [x] Site / templates are fully responsive built with mobile first appraoch

## Tasks
- [x] research fonts and color setup, define and document choice
- [x] setup base template and add all related links to the views
- [x] include login / signup link on main site

**Comment by rpf13** [comment]
The main template got enhanced via the new home view and the home.html template. This should extend the base template and show the unauthorized user the main site content, with the title and also the login, signup button.
Commit id: 582a9eb

**Comment by rpf13** [comment]
story will be set on hold, until final styling will be done.

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
