### ISSUE TITLE
USER STORY: Add "glow" effect to title on main site

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#29]
As a **Developer** I can **add a beautiful glow effect to the "The Collection" site main title** so that **the user will have a stunning effect, when visiting the main site**

## Acceptance Criteria
- [x] Glow boarder effect on main site's title "The Collection" is visible
- [x] Mobile & Desktop version need to show same result

## Tasks
- [x] research to implement effect with CSS or bootstrap effect
- [x] implement effect on title

**Comment by rpf13** [comment]
This story has been covered with the general styling story: https://github.com/rpf13/the-collection/issues/53
It will be closed.
