### ISSUE TITLE
USER STORY: Add navbar / hamburger menu

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#30]
As a **Developer** I can **add the main nav bar to the site** so that **a user can navigate through all content on the site**

## Acceptance Criteria
- [x] Navbar is added to the templates and it shows respective state (logged in, login, logout....) of buttons
- [x] On mobile, there is a hamburger menu present

## Tasks
- [x] Add respective navbar html bootstrap code to relevant templates
- [x] Make sure hamburger menu is visible on mobile
- [x] look and feel must be identical to main sites concept
- [x] update views and links, once navbar is present
- [x] make sure logic of user state / visible buttons are reflecting the related user login state

**Comment by rpf13** [comment]
Navbar has been updated to properly link the main site app as well as signup, login, logout.
Commit id: main 8591489

**Comment by rpf13** [comment]
Navbar got updated to reflect current state of implementation. It does also fix an issue that if a user is authenticated and clicks on the "The Collection" main title, he will be redirected to the collection_list.html site where as a not authenticated user will get send to home.html. This is done via the built in TemplateView class, which we are altering.If a user is not authenticated, the 'super()get....' method is called, which calls the parent class, which will then render the home.html template specified in teh template_name.
commit id: 49d3390

The navbar is also responsive and shrinks to a hamburger on small screens:


![Image](https://user-images.githubusercontent.com/25194462/232066827-f02cd6ef-6445-4d58-9078-18651591ec21.png)

**Comment by rpf13** [comment]
Story will be set to on hold, until final styling will be started and also the option of seeing the user in the navbar.

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
