### ISSUE TITLE
USER STORY: Add footer with social links

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#31]
As a **Developer** I can **add a footer with social links** so that **a user can get in touch with the project and the developers via social media**

## Acceptance Criteria
- [x] Footer is built and visible on all sites
- [x] Footer includes 3 social medial platforms
- [x] Footer is fully responsive on mobile as well as desktop
- [x] Look and Feel inline with rest of site

## Tasks
- [x] create / update templates with footer using bootstrap
- [x] use fontawesome for icons
- [x] update all templates and views with respective links

**Comment by rpf13** [comment]
This commit will add a footer, to some of the sites. It will add
it to the entry main site, once a user arrives and is unauthorised.
Furthermore it is added to the about site and the contact site.

The injection is done via the includes feature. Templates have been
updated due to this.

A custom css file has been added.
Styling still raw, will be finished later.
Commit id: fb2bd37

snapshot of the footer on the main entry site:



![Image](https://user-images.githubusercontent.com/25194462/235099904-b6f2007e-be71-4f37-833c-d6f522c99e7e.png)

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
