### ISSUE TITLE
USER STORY: Create a Collection

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#32]
As a **Developer** I can **create a Collection model, view & template** so that **I can save actual data for a new collection and display it**

## Acceptance Criteria
- [x] collection model is built and registered
- [x] collection view is created, template is done and urls are set
- [x] I am able to create a new collection and display it on the site

## Tasks
- [x] create the model and register it
- [x] create the view code (class based)
- [x] create the template to render the view
- [x] connect up the URL in the urls.py file
- [x] verify creation of a new collection

**Comment by rpf13** [comment]
initial version of model done and successfully created migration with commit 90055e3
```py
gitpod /workspace/the-collection (main) $ python3 manage.py makemigrations
Migrations for 'collection':
  collection/migrations/0001_initial.py
    - Create model Collection
    - Create model Item
    - Create model Image
gitpod /workspace/the-collection (main) $ 
gitpod /workspace/the-collection (main) $ 
gitpod /workspace/the-collection (main) $ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, collection, contenttypes, sessions
Running migrations:
  Applying collection.0001_initial... OK
gitpod /workspace/the-collection (main) $ 
```

**Comment by rpf13** [comment]
The collection overview has been adapted, even though still raw, but now it shows either a default image or the custom image.


![Image](https://user-images.githubusercontent.com/25194462/233108682-08c68ac1-a1a5-42e6-8a30-38994340127a.png)

Story will be set to on hold until final styling will take place.

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53

**Comment by rpf13** [comment]
This commit will add the full collection_description to the
collection_detail site, since on the collection_list site, inside each
collection card, the description text is truncated.
This will result in a better user experience.

commit id: a9986df

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236418089-bdc214e9-d7c2-4c79-bcf3-511eb132fd66.png)
