### ISSUE TITLE
USER STORY: Create Item(s)

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#33]
As a **Developer** I can **create an item(s) model, view & template** so that **a user can add items to his collections**

## Acceptance Criteria
- [x] item(s) model is built and registered
- [x] items view is created, template is done and urls are set
- [x] I am able to create multiple items withing a collection and display it on the site

## Tasks
- [x] create the model and register it
- [x] create the view code (class based)
- [x] create the template to render the view
- [x] connect up the URL in the urls.py file
- [x] verify creation of various items

**Comment by rpf13** [comment]
initial version of model done and successfully created migration with commit 90055e3
```py
gitpod /workspace/the-collection (main) $ python3 manage.py makemigrations
Migrations for 'collection':
  collection/migrations/0001_initial.py
    - Create model Collection
    - Create model Item
    - Create model Image
gitpod /workspace/the-collection (main) $ 
gitpod /workspace/the-collection (main) $ 
gitpod /workspace/the-collection (main) $ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, collection, contenttypes, sessions
Running migrations:
  Applying collection.0001_initial... OK
gitpod /workspace/the-collection (main) $ 
```

**Comment by rpf13** [comment]
The collection details view / item list view is created. If a user clicks on the "view" button of a collection, he can see all items in his collection.
However, if there are not items yet, a text box is displayed and a link to create items. Links to create or edit items are not active yet, will be done in future updates.
Styling is also very basic, will be enhanced later.

commit id: fb29ff3

Here a snapshot on how it looks, when a user clicks on the "View" button on the collection list:


![Image](https://user-images.githubusercontent.com/25194462/232061327-9bdf7d18-76c0-42be-9594-52525d41a512.png)

**Comment by rpf13** [comment]
I had to refactor the model for creating an item. I had to step back from the idea of having multiple images per item, since this has increased the level of complexity for the whole project quite a lot. Since I have to deliver MVP, I will let this feature for future implementation. I had to adapt the db model to reflect this.

Now it will be possible that the user can add one image per item.

commit id: e3213a3


The migration has been done to remove the image model
```py
Migrations for 'collection':
  collection/migrations/0002_auto_20230419_0653.py
    - Add field image to item
    - Delete model Image
gitpod /workspace/the-collection (main) $ python3 manage.py makemigrations
Migrations for 'collection':
  collection/migrations/0002_auto_20230419_0653.py
    - Add field image to item
    - Delete model Image
gitpod /workspace/the-collection (main) $ python manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, collection, contenttypes, sessions, sites, socialaccount
Running migrations:
  Applying collection.0002_auto_20230419_0653... OK
gitpod /workspace/the-collection (main) $ 

```

**Comment by rpf13** [comment]
This commit will add the create item template to look like the create
collection template. It is still basic and raw, but it works and
has the same look.
It is now possible to create a new item, upload an image or get a
default image and view the items in collection_detail view.

Commit id: 79705da

All following snapshots are raw, not final styling.
If there is no item in a collection, there is the option to create one, it will look like this:


![Image](https://user-images.githubusercontent.com/25194462/233103778-c1453516-b1a1-41b4-b31d-eaa9c8c3a5cd.png)

Once clicked, the form will open to create a item:


![Image](https://user-images.githubusercontent.com/25194462/233103987-2280d55f-eaed-46d2-a1ef-edb100edc539.png)

Once an item is created, in this case also showing a custom image, the user is redirected to the collection_detail view, where he can see all the items:



![Image](https://user-images.githubusercontent.com/25194462/233104421-af38e984-29e4-42af-b2f3-2f41bd82f064.png)

If there is no custom image, the default image will be provided:



![Image](https://user-images.githubusercontent.com/25194462/233104791-25b26025-669a-4150-a213-6512e5778a87.png)

**Comment by rpf13** [comment]
story will be set on hold, until final styling will be done.

**Comment by rpf13** [comment]
Pagination feature has been implemented for the collection detail view. It is set to 6 and will also display the current site in which the pagination is, in the url link.
commit id: 422f16f

Snapshot showing url and pagination:


![Image](https://user-images.githubusercontent.com/25194462/233684319-82d6fdca-8f13-4b01-9ee8-ef96afca4c0b.png)

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
