### ISSUE TITLE
USER STORY: Style & add navigation

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#34]
As a **Developer** I can **style the collection& items sites in the way that it reflects the overall design. Furthermore, I can update the navigation between the two as well as the rest of the app** so that **the user has a overall design experience throughout the whole app and can easily navigate between the sections.**

## Acceptance Criteria
- [ ] Style of collection and items section are inline with the overall styling concept and provide a integral design.
- [ ] It is simple to navigate between the main site, the collections and items, the flow is natural and the user does not have to search for any navigation - it is just there where it is needed.
- [ ] The listing of individual items is just correct in terms of quantity - to not overload the user's eye and gives a nice user experience.
- [ ] Site pagination is implemented at the correct amount of items / collections (final number has to be researched)
- [ ] If multiple pictures are added, they are displayed in a stylish way like cover flow or similar.

## Tasks
- [ ] enhance the styling to the collection and items site, adapt the templates as needed
- [ ] correct and update the navigation between the collections, items and the rest of the site to have a natural flow
- [ ] implement site pagination
- [ ] add cover flow (or similar feature) to the image section
- [ ] find "the right way" to display the details of an item (maybe modal or similar)

**Comment by rpf13** [comment]
All tasks have been implemented except the "multiple images" per item. This feature was de scoped from MVP.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
