### ISSUE TITLE
USER STORY: Add default image to collection and item

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#35]
As a **Developer** I can **add a generic image to a catalog and items by default** so that **the user has an nice look and feel even though he does not want to upload an image to a collection or item. **

## Acceptance Criteria
- [x] The collection has a default image in place
- [x] Each item has a default image in place
- [x] All of the default images can be replaced by custom image / upload

## Tasks
- [x] Find suitable generic images for catalog and items section
- [x] Implement the default set of such an image - update all templates as required
- [x] Make sure, individual images can replace the default image

**Comment by rpf13** [comment]
Even though this is not a must have feature, I did already implement it at this early stage, since by default a "icon" was loaded if no image was found. I found this ugly and since the logic of loading such an default image, combined with the logic required to have static files working with using "static" tag, was something I really had to look up and understand, it was worth doing it.
commit id: 8498a43

Here a collection list on how it looks with the default image:


![Image](https://user-images.githubusercontent.com/25194462/231984600-986d2e3c-89ac-49f3-9885-e71f20e232c7.png)

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
