### ISSUE TITLE
USER STORY: Create items search functionality

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#36]
As a **Developer** I can **create a search functionality inside a collection** so that **a user can search for items in a easy and very fast way.**

## Acceptance Criteria
- [x] Inside a collection, a search can be started and all fields of an item will be searchable
- [x] Site pagination for the results is in place

## Tasks
- [x] Create the option to execute a search inside a collection and only inside that particular collection, the user is currently in
- [x] All in the search function defined fields of an item should be searchable
- [x] create site pagination with the results, it should be very dynamic

**Comment by rpf13** [comment]
This commit will add a search functionality inside the collection_detail
view. It let's the user search for the given fields inside a
particular collection and only in that collection.

If search is successful, it wil display the result, if nothing is
found, it will display a text and a cancel button to return to the
collection where the user came from.

The feature is implemented inside / to work with pagination.

commit id: f518560

The following snapshot shows the search integration:


![Image](https://user-images.githubusercontent.com/25194462/233769978-9bc2ab46-9ed1-470c-ad05-d75f93851ef1.png)

The following snapshot shows a successful search after the description field content of an item, which is paginated (on site 2)



![Image](https://user-images.githubusercontent.com/25194462/233770049-5ccfc526-8c13-443e-9e83-8cb4c3439677.png)

The following snapshot shows a search without any results, displaying a text and a cancel button to return to the collection where the user came from



![Image](https://user-images.githubusercontent.com/25194462/233770081-a899d5f0-13d6-4d3c-8417-afd35515c0fa.png)

**Comment by rpf13** [comment]
Functionality is provided, styling is still raw but this will be done later. However, this story will be closed, since functionality is provided.
