### ISSUE TITLE
USER STORY: Adjust template to have search in place

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#37]
As a **Developer** I can **adjust the collection / items template** so that **the search field has a central place and has an integrated look and feel to the user so that it is obvious for a user to use the search.**

## Acceptance Criteria
- [x] The search function / field has to get added on a central place in the collections / items view
- [x] A search can be executed for any part of the content of an item - but it is limited to it

## Tasks
- [x] update the templates and place the search field centrally on the collections / items site
- [x] make sure it reflects the overall design and live results show up

**Comment by rpf13** [comment]
Look at the comments made in the functional story of the search, they contain the info for this story.
https://github.com/rpf13/the-collection/issues/36#issuecomment-1518547333
