### ISSUE TITLE
USER STORY: Create feedback site

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#38]
As a **Developer** I can **create a feedback site** so that **a user can get in contact with the developer / site owner**

## Acceptance Criteria
- [x] Feedback template is created and all necessary links are updated
- [x] The overall design reflects the design of the app
- [x] If a user submits a form, he will get a notification via modal, that the message has been successfully sent

## Tasks
- [x] Create a feedback site template with the same design as the other sites
- [x] Adjust all links and navbar - adjust also the authentication / user model in the way that only a user with the right permission can send feedback
- [x] Implement the same notification mechanism as for example for the user creation confirmation

**Comment by rpf13** [comment]
This commit will add the new contact app including the necessary
folder structure. It will also include the settings of the main
app urls.py as well as the settings.py

The contact app contains a new forms.py file, with a simple form.
The views.py got created and there are two Classes:
- The SendEmailView to wire up the form and create the data to be sent
- The EmailSuccessView to point to the success url.

Furthermore, it contains an urls.py file with the wiring of the two
classes to the contact.html and the success.html file.
The two .html file contan the very basic form data and success message.

Note that with this commit, the contact form is not functional, the
SendGrid Email Provider first needs to be wired up, which will be done in the next step.

The form already gets correctly displayed, a new nav button has been implemented:


![Image](https://user-images.githubusercontent.com/25194462/234018094-0ad4cada-7b42-41e6-8e4d-1e5421784855.png)

However, the success site is not get displayed yet, since it creates an error when executing the form_valid method in the class, since we call there the `settings.EMAIL_RECEIVE`, which I did not yet configure in the settings.py because I need to first get the SendGrid data.
Commit ID: 1d924c2

**Comment by rpf13** [comment]
Unfortunately I had to switch to Mailtrap, since I was not able to open an account with sendgrid. Anyway, much better, since the guide I have used to implement it: https://mailtrap.io/blog/django-contact-form/ was anyway from Mailtrap.

The settings.py got updated as well as the env.py, since the
credentials should not be exposed.

The contact.html and the success.html. got updated to be responsive,
but still very raw, needs to be updated later, when the whole app
will be styled.

The widget attribute has been used in the ContactForm class, in order
to set the placeholder in the form. Therefore the class ContactForm
in my custom forms.py file got updated.

The updated, but still raw, contact form looks like this:


![Image](https://user-images.githubusercontent.com/25194462/234045834-9ed6ae7d-2077-4dc7-9473-26b4dfd9bbb3.png)

The success message looks like this:


![Image](https://user-images.githubusercontent.com/25194462/234045947-588d1f43-617c-49fc-af99-e1eb41341d3e.png)

and finally, the Mailtrap GUI with the testemail is shown here as proof:


![Image](https://user-images.githubusercontent.com/25194462/234046237-7ae9dbd1-3bf5-48be-bbb3-33b98785ab5d.png)

commit id: 7df3b2a
