### ISSUE TITLE
USER STORY: Connect feedback form with email provider

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#39]
As a **Developer** I can **connect / implement the feedback form with a email provider like emailJS** so that **a user can actually send a real feedback, which the site owner will receive**

## Acceptance Criteria
- [x] emailJS (or any other email service if applicable) is implemented and once the user send a feedback message, a mail will be generated and received by the site owner (which is me as the main Developer)

## Tasks
- [ ] connect form to emailJS
- [x] create the email template and add functionality to the form template
- [x] connect site owner (me as Developer) gmail account to the service
- [x] test proper functionality

**Comment by rpf13** [comment]
Unfortunately I had to switch to Mailtrap, since I was not able to open an account with sendgrid. Anyway, much better, since the guide I have used to implement it: https://mailtrap.io/blog/django-contact-form/ was anyway from Mailtrap.

The settings.py got updated as well as the env.py, since the
credentials should not be exposed.

The contact.html and the success.html. got updated to be responsive,
but still very raw, needs to be updated later, when the whole app
will be styled.

The widget attribute has been used in the ContactForm class, in order
to set the placeholder in the form. Therefore the class ContactForm
in my custom forms.py file got updated.

The updated, but still raw, contact form looks like this:


![Image](https://user-images.githubusercontent.com/25194462/234045834-9ed6ae7d-2077-4dc7-9473-26b4dfd9bbb3.png)

The success message looks like this:


![Image](https://user-images.githubusercontent.com/25194462/234045947-588d1f43-617c-49fc-af99-e1eb41341d3e.png)

and finally, the Mailtrap GUI with the testemail is shown here as proof:


![Image](https://user-images.githubusercontent.com/25194462/234046237-7ae9dbd1-3bf5-48be-bbb3-33b98785ab5d.png)

commit id: 7df3b2a

**Comment by rpf13** [comment]
This commit will refactor the existing contact form settings in the
way, that it will no longer expose the EMAIL_RECEIVE mail address
to github. I have added it as an env var, also on heroku.
The setting is used to see in mailtrapp, to where the mail should
be forwarded. It is embedded int the particular view.

commit id: e0dead6
