### ISSUE TITLE
USER STORY: Create "About this site" page

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#40]
As a **Developer** I can **create an "About this site" page** so that **a user can understand and read what it is all about including legal aspects of content upload, terms and condition.**

## Acceptance Criteria
- [x] The "about this site" page is created, visible for users with the respective permissions and all the important info (especially the legal aspects) are clearly visible.
- [x] The look and feel matches the overall concept
- [x] Site navigation is updated, the page can be reached from the respective sources.

## Tasks
- [x] Create the "About this site" template and add all necessary info including legal note
- [x] Make the site available form the respective sources (update the authentication model)
- [x] Update all links / site navigation of the navbar

**Comment by rpf13** [comment]
This commit will add a simple "about" site to the app. A very simple
view has been created inside the collection app, since it is not worth
to create a new app just for this simple site.
The urls.py and the navbar got updated too.
The styling is still very raw, will be updated once the other sites get
styled.

Like everything else, this site is only available to logged in users.

commit id: f46ebb5

snapshot which shows about site and updated navbar



![Image](https://user-images.githubusercontent.com/25194462/234474968-018f0d71-b4af-4831-baf8-3a1c41a236de.png)
