### ISSUE TITLE
USER STORY: Create 403 http error site

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#41]
As a **Developer** I can **create a 403 Unauthorized error page** so that **so that an unauthorized user gets redirect and receives a useful error page, my views are secured**

## Acceptance Criteria
- [x] A 403 page is created and displayed to the user

## Tasks
- [x] create 403 page and implement it correctly in the base.html site
- [x] make sure the style matches the other error sites as well as the overall look and feel

**Comment by rpf13** [comment]
403 error site got implemented, CBV, urls.py and template got created for this.
However, could not find yet a way how to test it because all my content is behind Classes, which have the login decorator and check for that. If not, the user will be redirected to the login / account creation site. Need to find a way how to simulate that later.
Commit id: main 76871ba

**Comment by rpf13** [comment]
This commit will change the CBV for the error handling into
FBV. It will also move the error sites to a new folder in the root
app, called folders.
Since error sites need to be available for all apps, I had to move
them up in the hierarchy. Furthermore, I could not bring it up and
running with the CBV whne having in the root, so I decided to go
for FBV.
The CBV for the errors got deleted and in a new views.py of the main
app, the FBV are crated.
urls of the main app got enhanced with the error handler.

Now it should be the proper way how to handle errors for all apps.
commit id: f426f5f
