### ISSUE TITLE
USER STORY: Create 404 http error site

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#42]
As a **Developer** I can **create a 404 Not found error page** so that **so that a user gets redirect and receives a useful error page**

## Acceptance Criteria
- [x] A 404 page is created and displayed to the user

## Tasks
- [x] create 404 page and implement it correctly in the base.html site
- [x] make sure the style matches the other error sites as well as the overall look and feel

**Comment by rpf13** [comment]
To test this error, first I did set `DEBUG = False` in the settings.py. Then I did access a site, which does not exist and then I got successfully redirected to the 404 error site. Return to home link brought me back to the home view.
CBV, urls.py and templates have been built.
Commit id: main 76871ba

Error site snapshot:


![Image](https://user-images.githubusercontent.com/25194462/233842320-25977828-9cfa-4991-8c26-aa8a9f5bb400.png)

**Comment by rpf13** [comment]
This commit will change the CBV for the error handling into
FBV. It will also move the error sites to a new folder in the root
app, called folders.
Since error sites need to be available for all apps, I had to move
them up in the hierarchy. Furthermore, I could not bring it up and
running with the CBV whne having in the root, so I decided to go
for FBV.
The CBV for the errors got deleted and in a new views.py of the main
app, the FBV are crated.
urls of the main app got enhanced with the error handler.

Now it should be the proper way how to handle errors for all apps.
commit id: f426f5f
