### ISSUE TITLE
USER STORY: Create 500 http error site

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#43]
As a **Developer** I can **create a 500 server error page** so that **so that a user gets redirect and receives a useful error page**

## Acceptance Criteria
- [ ] A 500 page is created and displayed to the user

## Tasks
- [ ] create 500 page and implement it correctly in the base.html site
- [ ] make sure the style matches the other error sites as well as the overall look and feel

**Comment by rpf13** [comment]
To test this error, first I did set `DEBUG = False` in the settings.py. Then I have added the following code to the CollectionDetailView, the search function within:
```py

@method_decorator(login_required, name='dispatch')
class CollectionDetailView(LoginRequiredMixin, DetailView):
    model = Collection
    template_name = 'collection_detail.html'
    context_object_name = 'collection'
    paginate_by = 6

    def get_queryset(self):
        return Collection.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['collection_id'] = self.kwargs.get('pk')

        # code for search option of items
        search_query = self.request.GET.get('search', '')

        if search_query:
            raise Exception("This is a test 500 error.") # ====>>>>> This line has been added to raise a 500 error
            items = self.object.item_set.filter(
                Q(item_name__icontains=search_query)
                | Q(description__icontains=search_query)
                )
            context['search_performed'] = True
        else:
            items = self.object.item_set.all()
            context['search_performed'] = False
```

Once done, I did login, went o a collection detail and executed a search, which successfully brought me to the 500 error site. Return to home brought me correctly  back.
Commit id: main 76871

Snapshot of the error site:



![Image](https://user-images.githubusercontent.com/25194462/233842019-8ad62feb-c71f-4285-9703-da8f3a7735d2.png)

**Comment by rpf13** [comment]
This commit will change the CBV for the error handling into
FBV. It will also move the error sites to a new folder in the root
app, called folders.
Since error sites need to be available for all apps, I had to move
them up in the hierarchy. Furthermore, I could not bring it up and
running with the CBV whne having in the root, so I decided to go
for FBV.
The CBV for the errors got deleted and in a new views.py of the main
app, the FBV are crated.
urls of the main app got enhanced with the error handler.

Now it should be the proper way how to handle errors for all apps.
commit id: f426f5f
