### ISSUE TITLE
USER STORY: Create unit testing

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#44]
As a **Developer** I can **create unit testing with django integrated TestCaseClass** so that **I can execute automated testing and speed up the verification process**

## Acceptance Criteria
- [x] Setup Djanog unit testing and implement it in at least part of the code.
- [x] All created testcases must succeed.

## Tasks
- [x] Import the Django TestCase class and create dedicated unit test file
- [x] Create necessary testcases to cover at least one feature of the app
- [x] update the TESTING.md file accordingly with this automated testing

**Comment by rpf13** [comment]
I have created the initial setup using the local db.
commit id 8307d7a and 50bba82
I did setup an initial test set, created a mixin with common set setup attributes, a class for authenticated and a class for unauthenticated testcases.
The initial home view is tested for both classes. Test run successfully (after many errors and experimenting / fixing the code).
commit id: 7f4363d

```py
gitpod /workspace/the-collection (main) $ python3 manage.py test collection.tests
database = db.sqlite3
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

..
----------------------------------------------------------------------
Ran 2 tests in 0.258s

OK
Destroying test database for alias 'default'...
gitpod /workspace/the-collection (main) $ 
```

**Comment by rpf13** [comment]
Adding a few more testcases:
This commit will add a few more testcases to the collection app
testcases.
- simple test for collection_list view
- simple test for collection_detail view
- test for creating a new collection and testing response including
the redirect
commit id: 56d8da8

testoutput:

```py
gitpod /workspace/the-collection (main) $ python3 manage.py test collection.tests
database = db.sqlite3
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....
----------------------------------------------------------------------
Ran 5 tests in 0.761s

OK
Destroying test database for alias 'default'...
```

**Comment by rpf13** [comment]
additional testcases added:
This commit will add various additional testcaes for collection & items:
- test for update collection incl. response and redirect
- test for delete collection incl. response and redirect
- simple test to check collection detail view
- test for create new item inside testcollection incl redirect
- test for update item in testcollection incl. redirect
- test for delete item in testcollection incl. redirect

commit id: 8120e15

successful running 10 test at the moment:
```py
gitpod /workspace/the-collection (main) $ python3 manage.py test collection.tests
database = db.sqlite3
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..........
----------------------------------------------------------------------
Ran 10 tests in 1.682s

OK
Destroying test database for alias 'default'...
```

**Comment by rpf13** [comment]
This commit will add two more (simple) testcases to check
- access to item detail view with pre created data
- access to about site, which is also intentionally behind login wall

commit id: 80b8af8

There are now 12 testcases

```py
gitpod /workspace/the-collection (main) $ python3 manage.py test collection.tests 
database = db.sqlite3

............
----------------------------------------------------------------------
Ran 12 tests in 1.858s

OK
Destroying test database for alias 'default'...
```

**Comment by rpf13** [comment]
This commit will add two testcases for unauthenticated user.
- simple test to check redirect to accounts login if user wants to
create a new collection
- extensive test if user tries to add collection he will be redirected
to accounts login, logs in with pre created user data and creates a
new collection, which will be assessed.

commit id: b0adb19

There are now 14 testcases successfully passing:
```py

gitpod /workspace/the-collection (main) $ python3 manage.py test collection.tests 
database = db.sqlite3
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

..............
----------------------------------------------------------------------
Ran 14 tests in 2.029s

OK
Destroying test database for alias 'default'...
```

**Comment by rpf13** [comment]
The collection app has full coverage of automated unit testing. For the time being, I will leave it to this state. Maybe come back later to testing, if time is left to do some testing for the contacts app.

**Comment by rpf13** [comment]
all AC done, story will be closed.
