### ISSUE TITLE
USER STORY: Create README file

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#45]
As a **Developer** I can **create an extensive documentation of the project** so that **fellow developers can understand each step and part of my app and have the option to easily clone and recreate it**

## Acceptance Criteria
- [ ] Documentation is fully done on README.md, according to the requirements of the CI PP4
- [ ] All necessary links, images are correctly labelled and uploaded

## Tasks
- [ ] Create the readme and document each feature as described in the requirements document
- [ ] Include all screenshots and ERD, "Am I Responsive" coolor, ... snapshots

**Comment by rpf13** [comment]
A variety of commits have been done today to update the README file.

**Comment by rpf13** [comment]
This commit will add the feature description for the collection app as
well as some other parts of the application.
Images with snapshot of the individual sections are added.

commit id: 3127c00

**Comment by rpf13** [comment]
This commit will add the remaining parts for the feature description
section. It will also containt future features.

commit id: 28662a2

**Comment by rpf13** [comment]
Latest updates on readme done, finished.
