### ISSUE TITLE
USER STORY: Create TESTING file

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#46]
As a **Developer** I can **create an extensive testing documentation of the project** so that **fellow developers can understand each step I have taken to either manually or automatically test my project**

## Acceptance Criteria
- [ ] Testing Documentation is fully done on TESTING.md, according to the requirements of the CI PP4
- [ ] All necessary links, images are correctly labelled and uploaded
- [ ] Automated testing, if done in the unit testing section, is included and described

## Tasks
- [ ] Create the testing.md file and document each testing as described in the requirements document
- [ ] Include all screenshots and validation tool snapshots
- [ ] add the unit testing in case it was executed
- [ ] run code through all validators
- [ ] check lighthouse performance

**Comment by rpf13** [comment]
Testing Code HTML and CSS has been successfully executed and added to the testing file.

**Comment by rpf13** [comment]
This commit will add the CI python linter testing to the testing file.
It will also correct a few typos in the testing file.

commit id: dbfcd66

**Comment by rpf13** [comment]
This commit will add the user story testing chapter to the testing
documentation.
It will also add a missing feature test to the readme file.

commit id: 91f508c

**Comment by rpf13** [comment]
Lighthouse Testing chapter has been added.

commit id: 28f45d7

**Comment by rpf13** [comment]
Unit testing has been added to the TESTING.md file

commit id: 66f11bf

**Comment by rpf13** [comment]
This commit will add the browser testing chapter and the
responsiveness testing chapter to the TESTING file. It includes
a bunch of snapshots.

commit id: 4b77d6c

**Comment by rpf13** [comment]
Add "Defensive Programming" section to TESTING file.

commit id: 75d2a71

**Comment by rpf13** [comment]
Latest test data added / table for unit testing.
Story will be closed.
