### ISSUE TITLE
USER STORY: Submit final app

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#48]
As a **Developer** I can **submit my final app** so that **I fulfill the submission date of 31.5.2023 and the CI team can assess my PP4**

## Acceptance Criteria
- [x] All code is checked again and in perfect condition
- [x] All pass criteria of the assessment guide are fulfilled
- [x] Submission is done on time with all necessary info given to CI
- [x] Documentation is final

## Tasks
- [x] re-check again the **DEBUG SETTINGS**
- [x] re-read the assessment guide pass criteria and make sure all necessary tasks are done
- [x] recheck whole code, add comments where necessary and remove unwanted lines, comments
- [x] make sure the code and django file structure is in a perfect condition and enough test data is added to the app so that the assessor has a good picture of the app
- [x] check that documentation is in perfect state
- [x] submit on time, at least one working day before deadline

**Comment by rpf13** [comment]
Final project submitted on 18.5. 10:15 local time.
Project done, story done. :-)
