### ISSUE TITLE
USER STORY: Create & Verify admin user

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#50]
As a **developer** I can **create an admin / superuser** so that **I can login to the django admin panel and will be able to see newly created user profiles**

## Acceptance Criteria
- [x] Admin / Superuser created and able to login

## Tasks
- [x] create the superuser and verify login
- [x] at later step, once models are created, check if you can see individual user profiles.

**Comment by rpf13** [comment]
django admin user is created and tested to login.
The Collection and Item model is imported into the admin panel via simple `admin.site.register` method. This is done for two reasons:
1. to have all collections and items in admin panel, so admin can delete illegal content just from beginning
2. for further usage to add more functionality and maybe convert the registration also to decorators like `@admin.register` and also adding classes with filter functionality and other display filters to it. 

For now, basic implementation is done. Commit id ef8a517

**Comment by rpf13** [comment]
Admin site does now show accounts from other users, successfully implemented all tasks, will close.

snapshot:



![Image](https://user-images.githubusercontent.com/25194462/235627023-e5c28bdc-23d5-4239-bfa2-cabe7cadbc3e.png)
