### ISSUE TITLE
USER STORY: Update & Delete Collection

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#51]
As a **Developer** I can **create an update & delete model** so that **a registered user can update or delete one of his collections and all the related items**

## Acceptance Criteria
- [x] User can Update an existing collection description
- [x] User can delete an existing collection and all linked items

## Tasks
- [x] Create a new view to update a collection
- [x] Create a new view to delete a collection
- [x] Make sure the default image can be replaced by custom image
- [x] Create templates for update and delete view
- [x] Update all necessary links in other templates

**Comment by rpf13** [comment]
The following features have been implemented:

- Update view, in order to update an existing collection for name,
description or the image / replace the default image.

- Delete view, in order to delete a full collection, including a
security question to be sure for deletion. Since CASCADE is used in
the model, it will delete all items.

Templates, very generic, are also added as well as the existing
collection_list template got enhanced with the two more buttons.


Collection update form:

![Image](https://user-images.githubusercontent.com/25194462/232513624-c68d6e14-0197-47e1-a45d-39750d1e751f.png)

Collection Update Success:



![Image](https://user-images.githubusercontent.com/25194462/232513920-ef98b6b7-bed8-4aa3-a82c-5c21beb53a0f.png)

Collection Delete Form:



![Image](https://user-images.githubusercontent.com/25194462/232514021-365ce737-6c6d-4fa8-8576-02c3ca36d560.png)


Collection Delete Success:



![Image](https://user-images.githubusercontent.com/25194462/232514130-f947f7c9-930e-4f7f-80f9-dc3a5c12bf3a.png)

**Comment by rpf13** [comment]
Added the cancel button function when editing or
deleting a collection. Once pressed, it will point back to the
collection list.
commit id: f13eb74

**Comment by rpf13** [comment]
The deletion of a collection including all related items is working and tested, see snapshots.

Snapshot of collection to be deleted:



![Image](https://user-images.githubusercontent.com/25194462/233579032-6253e695-464d-4a54-afb6-4a7367b22909.png)

Snapshot of deleted collection including the item:



![Image](https://user-images.githubusercontent.com/25194462/233579105-e1ec39b4-0361-41c9-a78d-bdb8621396fe.png)

**Comment by rpf13** [comment]
Some functional buttons got added in order to navigate better. Styling still raw.
It will add a a edit collection, create item and my collections button.

commit id: 40ab346

Snapshot:


![Image](https://user-images.githubusercontent.com/25194462/233661826-50cce16a-0a3a-4e3d-8e63-18cbf3e751d1.png)

**Comment by rpf13** [comment]
Commit 40ab346 will also add a cancel button, in the create new collection view. It will bring the user back to the collection list.
Snapshot:



![Image](https://user-images.githubusercontent.com/25194462/233662183-71cf3317-cade-4704-a3b8-f17843c8ecb3.png)

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
