### ISSUE TITLE
USER STORY: Update & Delete Item

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#52]
As a **Developer** I can **create an update & delete model** so that **a registered user can update or delete one of his items**

## Acceptance Criteria
- [ ] User can Update an existing item description
- [ ] User can delete an existing item

## Tasks
- [ ] Create a new view to update an item
- [ ] Create a new view to delete an item
- [ ] Make sure the default image can be replaced by custom image
- [ ] Create templates for update and delete view
- [ ] Update all necessary links in other templates

**Comment by rpf13** [comment]
This commit will add the item update, delete & detail view including
the urls and the templates. They functionality is not entirely tested
yet, commit is done in order to save the code.

However, styling is still very raw and it will be changed later.
commit id: 5d82db4

**Comment by rpf13** [comment]
Item delete functionality is added including the templates. User will be prompted to confirm deletion. Styling is still raw, will be updated later.
commit id: f72248a

Snapshot of item deletion:


![Image](https://user-images.githubusercontent.com/25194462/233577806-439ed162-8f24-4897-affb-dbdce57ad1a3.png)

**Comment by rpf13** [comment]
New navigation buttons have been added in the create item view to cancel the creation. It will bring the user back to the collection list, from which he came from.
commit id: 40ab346

Snapshot:



![Image](https://user-images.githubusercontent.com/25194462/233662743-a7b43312-e41c-4c8a-a704-e03f61b64396.png)

**Comment by rpf13** [comment]
All tasks are done. Will close story.
Final styling will be handled with dedicated story: https://github.com/rpf13/the-collection/issues/53
