### ISSUE TITLE
USER STORY: Finalize Styling

### ISSUE THREAD

**Issue by rpf13** [rpf13/the-collection#53]
As a **Developer** I can **update the raw styling of the app** so that **the site looks nice, is responsive and reflects state of the art guidelines**

## Acceptance Criteria
- [ ] Styling concept for all sites
- [ ] Common rules for style and html code implemented
- [ ] Responsive design

## Tasks
- [ ] Modify bootstrap for all sites to reflect target style
- [ ] Add custom css file to add custom design
- [ ] Make sure responsiveness as well as accessibility concepts are implemented

**Comment by rpf13** [comment]
This commit will add an animated transient background to the body.
It will also overwrite the bootstrap navbar font, since accessibility
was not given with it.

commit id: b76ae04

**Comment by rpf13** [comment]
This commit will add an animated background to the main title of the
entry site.
It will also enhance the animated background to have a suitable style.

commit id: 5ec79ca

**Comment by rpf13** [comment]
This commit will add some more styling to the main site, adding some
text to the entry site.
It will also style the hover effect of the footer icons.

commit id: 6ef8033

**Comment by rpf13** [comment]
This commit will add final style to the main entry site, including
the navbar, home site and footer.
Media queries have been set to reduce font-size for very small
screens.

commit id: bc32a8a

snapshot (without animation)



![Image](https://user-images.githubusercontent.com/25194462/235869410-2c95c002-57dc-40df-a057-ea0640d54826.png)

**Comment by rpf13** [comment]
This commit will update the style of the collection list as well as
the collection create template to align with the overall look and
feel.

commit id: d88cda6

Snapshots of the styled versions:


![Image](https://user-images.githubusercontent.com/25194462/236123097-278483ef-1d70-4cf8-a610-e7657ecca4e3.png)
![Image](https://user-images.githubusercontent.com/25194462/236123098-8907477b-62a7-47b1-901f-92a0e0ac2f88.png)
![Image](https://user-images.githubusercontent.com/25194462/236123099-c67bae6a-618b-45e8-b06e-3597c383d33a.png)

**Comment by rpf13** [comment]
This commit will allign styling for the collection update site, to be
fully responsive and inline with the overall style.

commit id: 08798da

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236125306-41057f5e-e519-4c95-85ab-9cb93758e927.png)

**Comment by rpf13** [comment]
This commit will update the item update template with some
style to reflect the other sites.
It will also fix some minor tweaks on links, in order to have
correct redirection when pressing the buttons.

commit id: bb1c63b

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236167181-5baa7735-d2b6-48b7-a9de-f5f492d6acc7.png)

**Comment by rpf13** [comment]
This commit will style the item detail site and align it to the style
of the other sites.

commit id: f8152d5

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236203320-89960bf8-48e7-4571-b66e-b9e62de03e54.png)

**Comment by rpf13** [comment]
This commit will style the item create template in order to align
with the other templates. It will stay responsive, but getting centered.

commit id: f8989ae

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236211211-b0f68f2a-301b-473f-a362-bf40bdafc877.png)

**Comment by rpf13** [comment]
This commit will style the about site, align the text and make it
more appealing to the user. It will reflect the overall style.

commit id: 0c50684

snapshot:



![Image](https://user-images.githubusercontent.com/25194462/236219458-e6695d11-aea9-49f8-819e-9e0598536d24.png)

**Comment by rpf13** [comment]
This commit will style the links in the error sites in "white", in
order to achieve a good contrast.
The buttons on the contact and contact success site have been changed
to "white" in order to be inline with the design.

commit id: 53d0bb8

**Comment by rpf13** [comment]
This commit will update the collection delete template in the way to be
inline with look and feel to the other templates.

Commit id: 49283fb

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236754503-75ae39a1-7a1d-4710-9b8e-f2317395cf8a.png)

**Comment by rpf13** [comment]
This commit will update the item delete tempalte in order to be
inline with the style of the other templates.

commit id: b5f6ef1

snapshot:


![Image](https://user-images.githubusercontent.com/25194462/236764066-13217bea-dc31-4dc5-9682-63a3ea4527fc.png)

**Comment by rpf13** [comment]
Styling is done and after finishing almost all testing chapters, it is confirmed to be good. I will close story, if any styling issues pop up, a bug has to be opened.
